version: '3'
services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "4321:4321"
    command: sh -c "npm run dev -- --host 0.0.0.0"